name: Minify HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install minification tools
        run: |
          bun install

      - name: Minify CSS files
        run: |
          bun run minify:css

      - name: Commit and push changes
        env:
          USERNAME_GITEA: ${{ secrets.USERNAME_GITEA }}
          TOKEN_GITEA: ${{ secrets.TOKEN_GITEA }}
        run: |
          git config --global user.name "LibreCloud Actions Bot"
          git config --global user.email "git@pontusmail.org"
          git remote set-url origin https://${USERNAME_GITEA}:${TOKEN_GITEA}@git.pontusmail.org/aidan/pontus.git
          git add .
          git commit -m "[bot] Minifying CSS automatically"
          git push origin main
